routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * in this file we will define the routes for the admin panel
 * This routes will be accessed from a browser to handle the
 * backend content of the system.
 *
 * Authentication has been ignored here since this is a demo
 * App and its not meant to be used in real life situations.

*/
Route::get('/', 'IndexController@index');

/*
 * Here we define a group of routes with prefix admin, so that
 * user will be able to access all sub-routes with the URL
 * ourdomain/admin/*
 *
 * We also define the namespace as Admin, so that we can have all
 * our Controllers under the Admin folder for better organization
 * /Http/Controllers/Admin
 *
 * Here we will define resource routes, which help us to assign
 * typical CRUD (Create, Read, Update, Delete) routes to a controller
 *
 * More info here: https://laravel.com/docs/5.6/controllers#resource-controllers
 */
Route::namespace('Admin')->prefix('admin')->group(function () {

	//Define the routes for articles
	Route::resource('/articles', 'ArticleController');
	//Define the routes for authors
	Route::resource('/authors', 'AuthorController');
	//Define the routes for categories
	Route::resource('/categories', 'CategoryController');

	//Define a get route for the admin index page and assign the name admin to the route.
	//Naming the route will help us to easily reference the route in the app
	Route::get('/', 'AdminIndexController@index')->name('admin');
});

resources/views/inc/adminheader.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {{(Request::is('admin')?'active':'')}}">
                    <a class="nav-link" href="{{route('admin')}}">Articles <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {{(Request::segment(2) == "authors"?'active':'')}}">
                    <a class="nav-link" href="{{route('authors.index')}}">Authors</a>
                </li>
                <li class="nav-item {{(Request::segment(2) == "categories"?'active':'')}}">
                    <a class="nav-link" href="{{route('categories.index')}}">Categories</a>
                </li>
            </ul>
        </div>
    </div>

</nav>

resources/views/inc/footer.blade.php
<div class="copyright">
    <div class="container">
        © Copyright 2018 Christos Savva - Cocoon Creations Test App
    </div>
</div>

resources/views/inc/head.blade.php
<meta charset="utf-8">
<meta name="description" content="Coccons Test app">
<meta name="author" content="Christos Savva">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.css" rel="stylesheet">
<link rel="stylesheet" href="{{ URL::asset('css/style.css') }}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{{ URL::asset('js/scripts.js') }}"></script>
<title>Cocoons Test App</title>