routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * in this file we will define the routes for the admin panel
 * This routes will be accessed from a browser to handle the
 * backend content of the system.
 *
 * Authentication has been ignored here since this is a demo
 * App and its not meant to be used in real life situations.

*/
Route::get('/', 'IndexController@index');

/*
 * Here we define a group of routes with prefix admin, so that
 * user will be able to access all sub-routes with the URL
 * ourdomain/admin/*
 *
 * We also define the namespace as Admin, so that we can have all
 * our Controllers under the Admin folder for better organization
 * /Http/Controllers/Admin
 *
 * Here we will define resource routes, which help us to assign
 * typical CRUD (Create, Read, Update, Delete) routes to a controller
 *
 * More info here: https://laravel.com/docs/5.6/controllers#resource-controllers
 */
Route::namespace('Admin')->prefix('admin')->group(function () {

	//Define the routes for articles
	Route::resource('/articles', 'ArticleController');
	//Define the routes for authors
	Route::resource('/authors', 'AuthorController');
	//Define the routes for categories
	Route::resource('/categories', 'CategoryController');

	//Define a get route for the admin index page and assign the name admin to the route.
	//Naming the route will help us to easily reference the route in the app
	Route::get('/', 'AdminIndexController@index')->name('admin');
});

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
	protected $table = 'authors';
	protected $guarded = ['id', 'created_at', 'updated_at']; //safegurd that these attributes will not be fillable by anyone


	function articles()
	{
		return $this->hasMany('App\Article');
	}

	public function getFullNameAttribute($value)
	{
		return ucfirst($this->firstname) . ' ' . ucfirst($this->lastname);
	}
}

resources/views/admin/error.blade.php
@extends('layouts.admin')
@section('content')

    <div class="alert alert-danger">
        <strong>Ohh snap, something went wrong</strong>
        <p>{{$message}}</p>
        <p><strong><a href="{{route('admin')}}">Return back</a></strong></p>
    </div>
@stop

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Articles</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="action-bar">
                <a  href='{{ route('articles.create') }}' class="btn btn-primary">Compose New</a>
            </div>
        </div>
    </div>
    @if(session('status') )
        <div class="dismissible-alert alert alert-success">
            <strong>{{session('status')}}</strong>
        </div>
    @endif
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Summary</th>
            <th scope="col">Status</th>
            <th scope="col">Author</th>
            <th scope="col">Category</th>
            <th scope="col">Published</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($articles as $article)
            <tr>
                <td>{{$article->title}}</td>
                <td>{{$article->summary}}</td>
                <td>
                    @if($article->publishstatus == 0)
                        Unpublished
                    @elseif($article->publishstatus == 1)
                        Published
                    @else
                        Draft
                    @endif
                </td>
                <td>{{$article->author->full_name}}</td>
                <td>{{$article->category->categoryname}}</td>
                <td>{{$article->created_at}}</td>
                <td>
                    <a href='{{ route('articles.show', $article->id) }}' class="btn btn-primary"><span class="oi oi-eye"></span></a>
                    <a href="{{ route('articles.edit', $article->id) }}" class="btn btn-primary"><span class="oi-icon oi oi-pencil"></span></a>
                    {{ Form::open(array('route' => array('articles.destroy', $article->id), 'method' => 'DELETE', 'class' => 'delete-form')) }}
                    <button class="btn btn-danger">
                        <span class="oi oi-delete"></span>
                    </button>
                    {{ Form::close() }}
                </td>
            </tr>
        @endforeach

    </table>
@stop