routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * in this file we will define the routes for the admin panel
 * This routes will be accessed from a browser to handle the
 * backend content of the system.
 *
 * Authentication has been ignored here since this is a demo
 * App and its not meant to be used in real life situations.

*/
Route::get('/', 'IndexController@index');

/*
 * Here we define a group of routes with prefix admin, so that
 * user will be able to access all sub-routes with the URL
 * ourdomain/admin/*
 *
 * We also define the namespace as Admin, so that we can have all
 * our Controllers under the Admin folder for better organization
 * /Http/Controllers/Admin
 *
 * Here we will define resource routes, which help us to assign
 * typical CRUD (Create, Read, Update, Delete) routes to a controller
 *
 * More info here: https://laravel.com/docs/5.6/controllers#resource-controllers
 */
Route::namespace('Admin')->prefix('admin')->group(function () {

	//Define the routes for articles
	Route::resource('/articles', 'ArticleController');
	//Define the routes for authors
	Route::resource('/authors', 'AuthorController');
	//Define the routes for categories
	Route::resource('/categories', 'CategoryController');

	//Define a get route for the admin index page and assign the name admin to the route.
	//Naming the route will help us to easily reference the route in the app
	Route::get('/', 'AdminIndexController@index')->name('admin');
});

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
	protected $table = 'authors';
	protected $guarded = ['id', 'created_at', 'updated_at']; //safegurd that these attributes will not be fillable by anyone


	function articles()
	{
		return $this->hasMany('App\Article');
	}

	public function getFullNameAttribute($value)
	{
		return ucfirst($this->firstname) . ' ' . ucfirst($this->lastname);
	}
}

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\admin;

use App\Author;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $authors = Author::all();

	    return view('admin/authors/index')->with('authors', $authors);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
	    return view('admin/authors/create_author');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	    $validations = $request->validate([
		    'firstname' => 'required|max:100',
		    'lastname' => 'required|max:100',
	    ]);

	    $requestData = $request->all();

	    $newAuthor = new Author();
	    $newAuthor->fill($requestData);

	    if(!$newAuthor->save()){
		    return view('error', "Error while trying to save author.");
	    }

	    return redirect(route('authors.index'))->with('status', 'Author added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
	    return redirect(route('authors.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
	    $author = Author::find($id);
	    return view('admin/authors/update_author')->with(array('author'=> $author));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
	    $validations = $request->validate([
		    'firstname' => 'required|max:100',
		    'lastname' => 'required|max:100',
	    ]);

	    $author = Author::find($id);

	    if(!$author->update($request->all()))
		    return view('error', "Error while trying to save author.");

	    return redirect(route('authors.index'))->with('status', 'Author updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
	    $author = Author::find($id);

	    //We need to make sure that when deleting an auhtor there are no
	    //articles related to it, so we count how many articles are related
	    //to the author we are trying to delete.
	    $numOfArticles = $author->articles()->get()->count();
	    //in case the articles are more than 0, then we return an error
	    //letting the user know that the specific author cannot be deleted since there
	    //are articles related to it.
	    if($numOfArticles > 0)
		    return view('admin/error', array('message'=> "Cannot delete author, there is/are " . $numOfArticles . " assigned articles to this author."));

	    //if no articles are related then we try to delete, in case of an error we return an error
	    if(!$author->delete())
		    return view('error', "Error while trying to delete author.");

	    //if delete is successfull we return back to authors
	    return redirect(route('authors.index'))->with('status', 'Author deleted!');
    }
}

resources/views/admin/authors/create_author.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Create new Author</h1>

    @if($errors->any())
        <div class="alert alert-danger">
            <strong>We found the following error, please fix before saving: </strong>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {{ Form::open(array('route' => 'authors.store')) }}


    <div class="form-group @if($errors->has('firstname')) error @endif">
        {{ Form::label('firstname', 'First Name') }}
        {{ Form::text('firstname', '', array('class' => 'form-control')) }}
    </div>
    <div class="form-group @if($errors->has('lastname')) error @endif">
        {{ Form::label('lastname', 'Last Name') }}
        {{ Form::text('lastname', ' ', array('class' => 'form-control')) }}
    </div>
    {{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
    <a href="{{route('authors.index')}}" class="btn btn-secondary">Cancel</a>

    {{ Form::close() }}
@stop

resources/views/admin/authors/index.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Authors</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="action-bar">
                <a  href="{{ route('authors.create') }}" class="btn btn-primary">Create New</a>
            </div>
        </div>
    </div>
    @if(session('status') )
        <div class="dismissible-alert alert alert-success">
            <strong>{{session('status')}}</strong>
        </div>
    @endif
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Author Name</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($authors as $author)
            <tr>
                <td>{{$author->full_name}}</td>
                <td>
                    <a href="{{ route('authors.edit', $author->id) }}" class="btn btn-primary"><span class="oi oi-pencil"></span></a>
                    {{ Form::open(array('route' => array('authors.destroy', $author->id), 'method' => 'DELETE', 'class' => 'delete-form')) }}
                    <button class="btn btn-danger">
                        <span class="oi oi-delete"></span>
                    </button>
                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach

    </table>
@stop

resources/views/admin/authors/update_author.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Create new Author</h1>

    @if($errors->any())
        <div class="alert alert-danger">
            <strong>We found the following error, please fix before saving: </strong>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {{ Form::model($author, array('route' => array('authors.update', $author->id), 'method' => 'PUT')) }}


    <div class="form-group @if($errors->has('firstname')) error @endif">
        {{ Form::label('firstname', 'First Name') }}
        {{ Form::text('firstname', null, array('class' => 'form-control')) }}
    </div>
    <div class="form-group @if($errors->has('lastname')) error @endif">
        {{ Form::label('lastname', 'Last Name') }}
        {{ Form::text('lastname', null, array('class' => 'form-control')) }}
    </div>
    {{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
    <a href="{{route('authors.index')}}" class="btn btn-secondary">Cancel</a>


    {{ Form::close() }}
@stop