routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * in this file we will define the routes for the admin panel
 * This routes will be accessed from a browser to handle the
 * backend content of the system.
 *
 * Authentication has been ignored here since this is a demo
 * App and its not meant to be used in real life situations.

*/
Route::get('/', 'IndexController@index');

/*
 * Here we define a group of routes with prefix admin, so that
 * user will be able to access all sub-routes with the URL
 * ourdomain/admin/*
 *
 * We also define the namespace as Admin, so that we can have all
 * our Controllers under the Admin folder for better organization
 * /Http/Controllers/Admin
 *
 * Here we will define resource routes, which help us to assign
 * typical CRUD (Create, Read, Update, Delete) routes to a controller
 *
 * More info here: https://laravel.com/docs/5.6/controllers#resource-controllers
 */
Route::namespace('Admin')->prefix('admin')->group(function () {

	//Define the routes for articles
	Route::resource('/articles', 'ArticleController');
	//Define the routes for authors
	Route::resource('/authors', 'AuthorController');
	//Define the routes for categories
	Route::resource('/categories', 'CategoryController');

	//Define a get route for the admin index page and assign the name admin to the route.
	//Naming the route will help us to easily reference the route in the app
	Route::get('/', 'AdminIndexController@index')->name('admin');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
	protected $table = 'categories';
	protected $guarded = ['id', 'created_at', 'updated_at']; //safegurd that these attributes will not be fillable by anyone

	public function articles()
	{
		return $this->hasMany('App\Article');
	}
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $categories = Category::all();

	    return view('admin/categories/index')->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
	    return view('admin/categories/create_category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	    $validations = $request->validate([
		    'categoryname' => 'required|max:100'
	    ]);

	    $requestData = $request->all();

	    $newCat = new Category();
	    $newCat->fill($requestData);

	    if(!$newCat->save()){
		    return view('error', "Error while trying to save category.");
	    }

	    return redirect(route('categories.index'))->with('status', 'Category added!');;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
	    return redirect(route('categories.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
	    $cat = Category::find($id);
	    return view('admin/categories/update_categories')->with(array('category'=> $cat));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
	    $validations = $request->validate([
		    'categoryname' => 'required|max:100'
	    ]);

	    $cat = Category::find($id)->update($request->all());


	    return redirect(route('categories.index'))->with('status', 'Category updated!');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
	    //We need to make sure that when deleting a category there are no
	    //articles related to it, so we count how many articles are related
	    //to the category we are trying to delete.
	    $cat = Category::find($id);
		$numOfArticles = $cat->articles()->get()->count();
	    //in case the articles are more than 0, then we return an error
	    //letting the user know that the specific category cannot be deleted since there
	    //are articles related to it.
	    if($numOfArticles > 0)
		    return view('admin/error', array('message'=> "Cannot delete category, there are " . $numOfArticles . " assigned articles to this category."));

	    if(!$cat->delete())
		    return view('error', "Error while trying to delete category.");

	    return redirect(route('categories.index'))->with('status', 'Category deleted!');
    }
}

resources/views/admin/categories/create_category.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Create new Category</h1>

    @if($errors->any())
        <div class="alert alert-danger">
            <strong>We found the following error, please fix before saving: </strong>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {{ Form::open(array('route' => 'categories.store')) }}


    <div class="form-group @if($errors->has('categoryname')) error @endif">
        {{ Form::label('categoryname', 'Category Name') }}
        {{ Form::text('categoryname', '', array('class' => 'form-control')) }}
    </div>
    {{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
    <a href="{{route('categories.index')}}" class="btn btn-secondary">Cancel</a>

    {{ Form::close() }}
@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')
@section('content')

    <h1>Categories</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="action-bar">
                <a  href="{{ route('categories.create') }}" class="btn btn-primary">Create New</a>
            </div>
        </div>
    </div>
    @if(session('status') )
        <div class="dismissible-alert alert alert-success">
            <strong>{{session('status')}}</strong>
        </div>
    @endif
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Category Name</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
            <tr>
                <td>{{$category->categoryname}}</td>
                <td>
                    <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-primary"><span class="oi oi-pencil"></span></a>
                    {{ Form::open(array('route' => array('categories.destroy', $category->id), 'method' => 'DELETE', 'class' => 'delete-form')) }}
                    <button class="btn btn-danger">
                        <span class="oi oi-delete"></span>
                    </button>
                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach

    </table>
@stop

resources/views/admin/categories/update_categories.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Update Category</h1>

    @if($errors->any())
        <div class="alert alert-danger">
            <strong>We found the following error, please fix before saving: </strong>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {{ Form::model($category, array('route' => array('categories.update', $category->id), 'method' => 'PUT')) }}


    <div class="form-group @if($errors->has('categoryname')) error @endif">
        {{ Form::label('categoryname', 'Category Name') }}
        {{ Form::text('categoryname', null, array('class' => 'form-control')) }}
    </div>
    {{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
    <a href="{{route('categories.index')}}" class="btn btn-secondary">Cancel</a>

    {{ Form::close() }}
@stop